FROM tensorflow/tensorflow:2.16.1-gpu

RUN rm /etc/apt/sources.list.d/cuda.list

RUN apt-get update
RUN apt-get install -y unzip graphviz curl musescore3

RUN pip install --upgrade pip

WORKDIR /app

COPY ./requirements.txt /app
RUN pip intall -r /app/requirements.txt

COPY /notebooks/. /app/notebooks
COPY /scripts/. /app/scripts

ENV PYTHONPATH="${PYTHONPATH}:/app"